### ISSUE TITLE
Deleted files are not removed from the lint server

### ISSUE THREAD

**Issue by dchhetri** [pinterest/esprint#110]
Steps to reproduce

- Run esprint
- Add new file with known errors
- Run esprint and notices new file with known errors is reported as expected
- Delete new file with known errors
- Run esprint and notice the new file with known errors is still reported 

The solution at the moment was to run `esprint stop` then `esprint` which basically restarts the server

**Comment by christianvuerings** [comment]
I was able to repro on previous versions on esprint but it looks fine on more recent versions. @dchhetri could you give it another try?

We also have a test which should explicitly test this case: https://github.com/pinterest/esprint/blob/master/tests/file-deletion/__tests__/file-deletion.test.js
