### ISSUE TITLE
Why is the dnode dependency a GitHub URL?

### ISSUE THREAD

**Issue by kaiyoma** [pinterest/esprint#118]
I noticed an unusual error recently during `yarn install` in my project:

```
fatal: unable to access 'https://github.com/christianvuerings/dnode/': Failed to connect to github.com port 443: Connection timed out
```

It seems very unconventional for any connection to GitHub, so I looked up where this came from:

```
$ yarn why dnode
yarn why v1.22.0
[1/4] Why do we have the module "dnode"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "dnode@1.2.2"
info Reasons this module exists
   - "esprint" depends on it
   - Hoisted from "esprint#dnode"
Done in 2.08s.
```

Sure enough, when I look in `package.json` in this repo, I see this:

```
"dnode": "https://github.com/christianvuerings/dnode#e08e620b18c9086d47fe68e08328b19465c62fb7",
```

Why is this URL being used instead of the normal npm package? This seems highly unusual to me and a lot less reliable than pulling the package from npm. If that repo ever becomes unavailable (like if GitHub is down or the user deletes the repo), then all installs of esprint will fail. This wouldn't happen with npm packages since old versions are never taken down.

**Comment by mahirshah** [comment]
+1 on this issue, would love to understand why the dnode dependency points to the github url as I am running into the same issue

**Comment by christianvuerings** [comment]
Fixed as part of https://github.com/pinterest/esprint/pull/119 where we use `dnode-weak-ngapi` instead
