### ISSUE TITLE
esprint linting job hits ENOMEM errors, but task does not fail

### ISSUE THREAD

**Issue by caitlinard** [pinterest/esprint#121]
Hey there,

I installed esprint (^0.7.0) with yarn (1.12.3) and am running `yarn esprint check` with a list of ~1k files as xargs.
I was at first experiencing ENOMEM failures, but then started using a circleci node with `resource_class: large` (4 vCPUs and 8GB RAM) which caused the job to pass.
However, when I look at the output it looks like I am still hitting `Error: ENOMEM: not enough memory, read` at the beginning of the run.

It appears esprint keeps retrying after running out of memory and the job eventually succeeds - can you confirm that this is the case?

If so, it looks like the retries cause the task to take about as long as running eslint. Let me know where I could be going wrong here.

Thanks!

**Comment by christianvuerings** [comment]
@caitlinard could you see if this is still an issue with the the latest version of esprint? Closing for now but feel free to re-open
