### ISSUE TITLE
Use something like `babel-register` to compile code on the fly

### ISSUE THREAD

**Issue by akleiner2** [pinterest/esprint#57]
Right now, we have to run `yarn run start` in a separate terminal tab in order to watch for code changes and compile them back down to ES5. `babel-register` would make developing for esprint a bit easier.

**Comment by arthuralee** [comment]
In dev only I'm assuming?

**Comment by akleiner2** [comment]
Yep

**Comment by milesj** [comment]
Your eslint config should be using the `babel-eslint` parser?

**Comment by arthuralee** [comment]
@milesj good catch - looks like #60 fixes that
