### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by omerzach** [pinterest/esprint#70]
Can we get a new release? Would love to update to a version with https://github.com/pinterest/esprint/commit/fa407b9f5942b83c05cbe6810357c69b5caf9b7d.

**Comment by akleiner2** [comment]
@omerzach We're looking into cutting a release today. Thanks for the nudge :)

**Comment by akleiner2** [comment]
`esprint@0.4.0` (non-beta) is out! Feel free to update and let us know if you have any other issues!
