### ISSUE TITLE
Does not work properly with lint-staged

### ISSUE THREAD

**Issue by iOiurson** [pinterest/esprint#72]
Hello,

it seems that `esprint` used with [`lint-staged`](https://github.com/okonet/lint-staged) still lints all files instead of only the files staged.

Is there an option to set to make it work correctly with `lint-staged` ?

**Comment by akleiner2** [comment]
Hey @iOiurson I have not looked too much into `lint-staged`. Do you have a sample config to take a look at?

**Comment by iOiurson** [comment]
Basically the one provided by `lint-staged` docs, but with `esprint` instead of `eslint`:
```
{
  "scripts": {
    "precommit": "lint-staged"
  },
  "lint-staged": {
    "*.js": ["esprint check"]
  }
}
```

Using `esprint` still lint all files in the folder, while using `eslint` lint only staged files.
