### ISSUE TITLE
Merge esprint into eslint

### ISSUE THREAD

**Issue by GauthierPLM** [pinterest/esprint#73]
Esprint is the tool that ESlint needed to be usable in a fast development workflow. It speeds up a lot the work.
That why I think it would be an awesome addition to ESlint itself. It would improve the life of many dev and would faster a lot it's daily usage.

It could be available via a `--watch` option, like what is available for jest.

**Comment by lasergoat** [comment]
@Kendos-Kenlen have they discussed it on the eslint side?

**Comment by Kendos-Kenlen** [comment]
Not as far as I know.

**Comment by yvele** [comment]
Super related to https://github.com/eslint/eslint/issues/3565

**Comment by bradencanderson** [comment]
We'll take direction from the eslint maintainers here. They're totally free to point to a blessed third-party solution or build a first-party one as part of eslint core.

**Comment by christianvuerings** [comment]
Let's continue this conversation in https://github.com/eslint/eslint/issues/3565 and https://github.com/eslint/rfcs/pull/42
