### ISSUE TITLE
error  'propTypes' is not defined  when using Esprint

### ISSUE THREAD

**Issue by EricZhaoCherryTomato** [pinterest/esprint#77]
Got error  'propTypes' is not defined no-undef when running esprint but works fine when using eslint.

Is esprint using fixed version of eslint and babel-lint?

**Comment by christianvuerings** [comment]
> Is esprint using fixed version of eslint and babel-lint?
We use the eslint version which is installed as a peer dependency

Please provide a valid repro case if this is still an issue.
