### ISSUE TITLE
`esprint check --workers=2` consistently hangs on Windows

### ISSUE THREAD

**Issue by kaiyoma** [pinterest/esprint#79]
`esprint check` is just fine (and seems to spawn 4 workers, based on the output of Task Manager), but manually specifying `--workers=2` causes the process to hang.

It seems to actually do the linting (again, based on what I'm seeing in Task Manager), but once the Node processes disappear, control is never returned to the shell.

**Comment by christianvuerings** [comment]
We moved from dnode to jayson and upgraded all of our dependencies - please try this again on the latest version of esprint.
