### ISSUE TITLE
Wrong version published on NPM 

### ISSUE THREAD

**Issue by honeydripper** [pinterest/esprint#80]
It seems that the latest published version on npm does not correspond to source code here. Specifically the code for supporting the --quiet option is missing.

Do you think you could publish updated package or make a new release?

**Comment by kaiyoma** [comment]
I would like a release as well, especially since there hasn't been a release in over 15 months. I need this command-line option: https://github.com/pinterest/esprint/pull/75

**Comment by jakesyl** [comment]
@it-pinterest

**Comment by mdio** [comment]
Hey. We've released a fork of the current master as 0.5.0 under https://www.npmjs.com/package/@researchgate/esprint

**Comment by fvgs** [comment]
Hey folks, I've released and published [v0.5.0](https://github.com/pinterest/esprint/releases/tag/v0.5.0) with the latest changes (hopefully better late than never 😉)
